spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:tcp://localhost/~/test2
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#token:
#  expiration_time: 86400000
#  secret: ekswlsmstptkddptjrkwkdrnldudnsalsldjcuvlsturkddkwl