spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/test2
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

token:
  expiration_time: 86400000
  secret: ekswlsmstptkddptjrkwkdrnldudnsalsldjcuvlsturkddkwl